# This is a basic workflow to help you get started with Actions

name: Sender

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Working
      env:
        SENDER: ${{ secrets.SENDER }}
        TO: ${{ secrets.TO }}
        PASS_KEY: ${{ secrets.PASS_KEY }}
      run: python main.py